spring.application.name=core-api
spring.profiles.default=local

server.port=8081

management.endpoints.web.exposure.include=health,info,metrics

springdoc.swagger-ui.path=/swagger-ui.html

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=21MB

app.storage.prontuario.path=${PRONTUARIO_STORAGE_PATH:./storage/prontuarios}